export default [
  {
    eventImage: "summer_work.jpg",
    eventName: "Volunteering Opportunities",
    eventType: "major",
    eventDay: "",
    eventTime: "",
    eventSpeaker1: "Cynthia Li",
    eventSpeaker2: "Vibha Vijay",
    speakerBackground: "Boston University & University of Minnesota",
  },
  {
    eventImage: "pre-med.jpg",
    eventName: "Volunteering Opportunities",
    eventType: "career",
    eventDay: "4/28/2022",
    eventTime: "",
    eventSpeaker1: "Victor A Schingo",
    eventSpeaker2: "Vibha Vijay",
    speakerBackground: "Boston University & University of Minnesota",
  },
  {
    eventImage: "research.jpg",
    eventName: "Pre-Med 101",
    eventType: "skill",
    eventDay: "",
    eventTime: "",
    eventSpeaker1: "Kenai Dindia",
    eventSpeaker2: "Maurycy Filecki",
    speakerBackground: "Boston University & University of Minnesota",
  },
  {
    eventImage: "pre-med.jpg",
    eventName: "Pre-Med 101",
    eventType: "skill",
    eventDay: "4/28/2022",
    eventTime: "4:00 PM PT",
    eventSpeaker1: "Victor A Schingo",
    eventSpeaker2: "",
    speakerBackground: "Boston University & University of Minnesota",
  },
  {
    eventImage: "pre-med.jpg",
    eventName: "Pre-Med 101",
    eventType: "career",
    eventDay: "4/28/2022",
    eventTime: "4:00 PM PT",
    eventSpeaker1: "Kenai Dindia",
    eventSpeaker2: "Vibha Vijay",
    speakerBackground: "Harvard University",
  },
  {
    eventImage: "pre-med.jpg",
    eventName: "Pre-Med 101",
    eventType: "major",
    eventDay: "3/29/2022",
    eventTime: "",
    eventSpeaker1: "Kenai Dindia",
    eventSpeaker2: "",
    speakerBackground: "Washington University in St. Louis",
  },
  {
    eventImage: "pre-med.jpg",
    eventName: "How to Spend Your Summers",
    eventType: "skill",
    eventDay: "3/29/2022",
    eventTime: "",
    eventSpeaker1: "Katherine Wilcox",
    eventSpeaker2: "Malvika Kuncham",
    speakerBackground: "Washington University in St. Louis",
  },
  {
    eventImage: "volunteering.jpg",
    eventName: "Volunteering Opportunities",
    eventType: "major",
    eventDay: "",
    eventTime: "",
    eventSpeaker1: "Katherine Wilcox",
    eventSpeaker2: "Malvika Kuncham",
    speakerBackground: "Washington University in St. Louis",
  },
  {
    eventImage: "volunteering.jpg",
    eventName: "Pre-Med 101",
    eventType: "skill",
    eventDay: "4/2/2022",
    eventTime: "7:00 PM ET",
    eventSpeaker1: "Cynthia Li",
    eventSpeaker2: "Maurycy Filecki",
    speakerBackground: "University of Washington",
  },
  {
    eventImage: "research.jpg",
    eventName: "Introduction to Research",
    eventType: "skill",
    eventDay: "4/28/2022",
    eventTime: "7:00 PM ET",
    eventSpeaker1: "Katherine Wilcox",
    eventSpeaker2: "Maurycy Filecki",
    speakerBackground: "Harvard University",
  },
  {
    eventImage: "pre-med.jpg",
    eventName: "How to Spend Your Summers",
    eventType: "skill",
    eventDay: "",
    eventTime: "4:00 PM PT",
    eventSpeaker1: "Katherine Wilcox",
    eventSpeaker2: "",
    speakerBackground: "University of Washington",
  },
  {
    eventImage: "summer_work.jpg",
    eventName: "Introduction to Research",
    eventType: "skill",
    eventDay: "",
    eventTime: "4:00 PM PT",
    eventSpeaker1: "Victor A Schingo",
    eventSpeaker2: "Maurycy Filecki",
    speakerBackground: "Boston University & University of Minnesota",
  },
  {
    eventImage: "research.jpg",
    eventName: "Introduction to Research",
    eventType: "major",
    eventDay: "3/29/2022",
    eventTime: "",
    eventSpeaker1: "Kenai Dindia",
    eventSpeaker2: "",
    speakerBackground: "Boston University & University of Minnesota",
  },
  {
    eventImage: "pre-med.jpg",
    eventName: "Volunteering Opportunities",
    eventType: "skill",
    eventDay: "",
    eventTime: "4:00 PM PT",
    eventSpeaker1: "Katherine Wilcox",
    eventSpeaker2: "",
    speakerBackground: "University of Washington",
  },
  {
    eventImage: "summer_work.jpg",
    eventName: "Introduction to Research",
    eventType: "skill",
    eventDay: "4/2/2022",
    eventTime: "",
    eventSpeaker1: "Kenai Dindia",
    eventSpeaker2: "Maurycy Filecki",
    speakerBackground: "Boston University & University of Minnesota",
  },
  {
    eventImage: "volunteering.jpg",
    eventName: "Pre-Med 101",
    eventType: "career",
    eventDay: "4/2/2022",
    eventTime: "",
    eventSpeaker1: "Kenai Dindia",
    eventSpeaker2: "",
    speakerBackground: "Boston University & University of Minnesota",
  },
  {
    eventImage: "summer_work.jpg",
    eventName: "Volunteering Opportunities",
    eventType: "skill",
    eventDay: "4/28/2022",
    eventTime: "7:00 PM ET",
    eventSpeaker1: "Kenai Dindia",
    eventSpeaker2: "Vibha Vijay",
    speakerBackground: "University of Washington",
  },
  {
    eventImage: "research.jpg",
    eventName: "Pre-Med 101",
    eventType: "skill",
    eventDay: "4/2/2022",
    eventTime: "",
    eventSpeaker1: "Victor A Schingo",
    eventSpeaker2: "Malvika Kuncham",
    speakerBackground: "University of Washington",
  },
  {
    eventImage: "summer_work.jpg",
    eventName: "Introduction to Research",
    eventType: "skill",
    eventDay: "4/28/2022",
    eventTime: "4:00 PM PT",
    eventSpeaker1: "Victor A Schingo",
    eventSpeaker2: "Malvika Kuncham",
    speakerBackground: "Boston University & University of Minnesota",
  },
  {
    eventImage: "volunteering.jpg",
    eventName: "Pre-Med 101",
    eventType: "major",
    eventDay: "3/29/2022",
    eventTime: "7:00 PM ET",
    eventSpeaker1: "Victor A Schingo",
    eventSpeaker2: "Malvika Kuncham",
    speakerBackground: "Boston University & University of Minnesota",
  },
  {
    eventImage: "summer_work.jpg",
    eventName: "How to Spend Your Summers",
    eventType: "career",
    eventDay: "3/29/2022",
    eventTime: "7:00 PM ET",
    eventSpeaker1: "Cynthia Li",
    eventSpeaker2: "",
    speakerBackground: "Boston University & University of Minnesota",
  },
  {
    eventImage: "pre-med.jpg",
    eventName: "How to Spend Your Summers",
    eventType: "skill",
    eventDay: "4/2/2022",
    eventTime: "",
    eventSpeaker1: "Victor A Schingo",
    eventSpeaker2: "",
    speakerBackground: "University of Washington",
  },
  {
    eventImage: "research.jpg",
    eventName: "Introduction to Research",
    eventType: "skill",
    eventDay: "",
    eventTime: "",
    eventSpeaker1: "Kenai Dindia",
    eventSpeaker2: "Maurycy Filecki",
    speakerBackground: "Harvard University",
  },
  {
    eventImage: "pre-med.jpg",
    eventName: "Pre-Med 101",
    eventType: "skill",
    eventDay: "",
    eventTime: "4:00 PM PT",
    eventSpeaker1: "Victor A Schingo",
    eventSpeaker2: "",
    speakerBackground: "Harvard University",
  },
  {
    eventImage: "summer_work.jpg",
    eventName: "Volunteering Opportunities",
    eventType: "major",
    eventDay: "3/29/2022",
    eventTime: "",
    eventSpeaker1: "Cynthia Li",
    eventSpeaker2: "Maurycy Filecki",
    speakerBackground: "Boston University & University of Minnesota",
  },
  {
    eventImage: "pre-med.jpg",
    eventName: "Volunteering Opportunities",
    eventType: "skill",
    eventDay: "4/2/2022",
    eventTime: "",
    eventSpeaker1: "Katherine Wilcox",
    eventSpeaker2: "",
    speakerBackground: "Boston University & University of Minnesota",
  },
  {
    eventImage: "research.jpg",
    eventName: "How to Spend Your Summers",
    eventType: "skill",
    eventDay: "",
    eventTime: "4:00 PM PT",
    eventSpeaker1: "Katherine Wilcox",
    eventSpeaker2: "Vibha Vijay",
    speakerBackground: "University of Washington",
  },
  {
    eventImage: "pre-med.jpg",
    eventName: "How to Spend Your Summers",
    eventType: "skill",
    eventDay: "3/29/2022",
    eventTime: "4:00 PM PT",
    eventSpeaker1: "Katherine Wilcox",
    eventSpeaker2: "Malvika Kuncham",
    speakerBackground: "University of Washington",
  },
  {
    eventImage: "summer_work.jpg",
    eventName: "Introduction to Research",
    eventType: "skill",
    eventDay: "4/28/2022",
    eventTime: "",
    eventSpeaker1: "Kenai Dindia",
    eventSpeaker2: "Malvika Kuncham",
    speakerBackground: "Washington University in St. Louis",
  },
  {
    eventImage: "research.jpg",
    eventName: "Volunteering Opportunities",
    eventType: "skill",
    eventDay: "",
    eventTime: "4:00 PM PT",
    eventSpeaker1: "Victor A Schingo",
    eventSpeaker2: "Vibha Vijay",
    speakerBackground: "Boston University & University of Minnesota",
  },
];
